version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: debugmate-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=debugmate
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - debugmate-network
    restart: unless-stopped

  debugmate-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: debugmate-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://trolley.proxy.rlwy.net:49425/railway
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=yHFzQilzZRIEafREPHCRssSpSqqKUFjQ
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - postgres
    networks:
      - debugmate-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  debugmate-network:
    driver: bridge
